### ISSUE TITLE
Crashes with Biomes O Plenty

### ISSUE THREAD

**Issue by BBoldt** [TeamDmfMM/Extra-Food#26] opened 2016-01-19 07:36 UTC
https://github.com/Glitchfiend/BiomesOPlenty/issues/611

**Comment by mincrmatt12** [comment] 2016-01-19 15:10
Just read that issue, looking in to it.

**Comment by DoughnutDev** [comment] 2016-01-26 22:39
Having this same issue on 3.0.0.1743 of Biomes O Plenty and I am using ExtraFoods 0.7.51.

**Comment by dmf444** [comment] 2016-02-21 23:03
Unable to reproduce. If possible, can I have a world download?

**Comment by Morpheus1101** [comment] 2016-05-04 01:30
Has the release that fixes this issue been released yet?  If it has then im still getting an error.

http://pastebin.com/Vd8ZF3Vy

**Comment by dmf444** [comment] 2016-05-04 03:06
I thought I had fixed this... Looks like I have to check again

**Comment by Morpheus1101** [comment] 2016-05-06 22:29
It does get annoying when that happens

**Comment by mincrmatt12** [comment] 2016-05-08 11:37
So after reading the crash log again, and then reading the bit that it's crashing on, I have come to a very clear conclusion: this was never fixed. Luckily, I figured out how to fix it and this should be fixed in the next commit

**Comment by mincrmatt12** [comment] 2016-05-12 23:48
darn it didn't work...

**Comment by mincrmatt12** [comment] 2016-05-13 00:00
And now its fixed. Not closing until released, though

**Closed** 2016-05-13 00:49 UTC
Labels: FIXED - Next Release
